<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create</name>
   <tag></tag>
   <elementGuidId>792f9e25-ddfb-4626-81c9-6fa253ed16a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.bg-brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' bg-brand ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f84554c-1ab2-48bd-a634-7577c5e9bf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0d9b2079-b896-480a-84b7-071dcc172190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-black bg-brand hover:bg-brand-light box-border border border-transparent font-medium leading-5 rounded-full text-sm px-8 py-2.5 transition-colors</value>
      <webElementGuid>b8d56523-fd04-4d9e-bb64-bed63a1f14f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Create
            </value>
      <webElementGuid>0c0a6289-9ca7-40c2-8573-ad0a599b791a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bd8ef96a366329a60b5430f114b7f9ec</value>
      <webElementGuid>da3f1bfc-25db-442b-929a-8003003cfeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' bg-brand ')]</value>
      <webElementGuid>b9ab5427-5e90-4980-8475-2e1ced304910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' bg-brand ')]</value>
      <webElementGuid>f0f04837-2c45-4205-9590-a51599df5a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                Create
            ' or . = '
                Create
            ')]</value>
      <webElementGuid>10f0b294-9329-4207-a126-3d176e1c2166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
