<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Image</name>
   <tag></tag>
   <elementGuidId>bf1beda9-99fe-4188-845f-e9f295dce99c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#image_path</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'image_path']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e94772ea-82ea-42ef-9cdc-c272a52e56c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d446ad20-4532-4090-ade8-a78b46fc9450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image_path</value>
      <webElementGuid>849e3b14-484e-4542-8fb2-35c3c541b379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>image_path</value>
      <webElementGuid>1b4003ae-80c6-4b3a-8ff4-7f48950fbbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-black border border-default-medium rounded-lg text-heading text-base focus:ring-brand focus:outline-[#7ae0d3] block w-full px-3.5 py-3 shadow-xs placeholder:text-body</value>
      <webElementGuid>b6122b52-c2a3-448f-adb2-af6bfa6b3da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-db9708ca9042e733de3b4bc2c16beb0e</value>
      <webElementGuid>43901c96-1657-4e2d-ac1a-212049ede4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'image_path']</value>
      <webElementGuid>1547a77b-2ccf-460a-826a-11db71412f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'image_path']</value>
      <webElementGuid>6ed1a901-a03f-483f-82c6-e57d1c858c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'image_path' and @name = 'image_path']</value>
      <webElementGuid>49914a42-3b64-4a59-b91c-f523cb60840e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
