<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_hr-separator</name>
   <tag></tag>
   <elementGuidId>635810ec-7cbf-4a6e-81c7-d9d97d83566a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.hr-separator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hr-separator ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>227fa08a-f2f3-491a-a076-5a6437f29806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hr-separator</value>
      <webElementGuid>0812032d-175a-48fc-8789-d694ab5b2285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b3a12cb783de9d5a95ccffe6ab2340be</value>
      <webElementGuid>e8b667a4-9552-462c-af6f-e91f28b031eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hr-separator ')]</value>
      <webElementGuid>8446558c-f128-4561-b6ad-dec780a7b3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout  ReTide Marketplace/iframe_snap-midtrans</value>
      <webElementGuid>6705ac03-ae1b-4e77-8075-e4767994e5de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' hr-separator ')]</value>
      <webElementGuid>c1b0930c-c91e-47d4-a951-b1759b04e38e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
