name: Tests

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: pcov

    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install NPM Dependencies
      run: npm install

    - name: Prepare Laravel Environment
      run: |
        mkdir -p bootstrap/cache
        cp .env.example .env
        php artisan key:generate
        touch database/database.sqlite

    - name: Build Frontend Assets
      run: npm run build

    - name: Run Code Coverage Test
      run: php artisan test --coverage --min=0
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
